baseURL = 'https://sawwheet.com/'
languageCode = 'en-us'
title = 'Sawwheet'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10
	[[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 20
		[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30

[module]
[[module.imports]]
path = "github.com/hugo-sid/hugo-blog-awesome"
